# Generated by Django 5.2.5 on 2025-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='bride_firstname',
            field=models.CharField(default='', max_length=100, verbose_name='신부 이름'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_lastname',
            field=models.CharField(default='', max_length=100, verbose_name='신부 성'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_firstname',
            field=models.CharField(default='', max_length=100, verbose_name='신랑 이름'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_lastname',
            field=models.CharField(default='', max_length=100, verbose_name='신랑 성'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='wedding_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결혼식 날짜'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='weddinghall_info',
            field=models.CharField(default='', max_length=200, verbose_name='웨딩홀 정보'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='weddinghall_name',
            field=models.CharField(default='', max_length=100, verbose_name='결혼식장 이름'),
        ),
    ]
