# Generated by Django 5.2.5 on 2025-09-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0003_alter_invitation_bride_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='app_invitation.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.SmallIntegerField(choices=[(1, '신랑측'), (2, '신부측')])),
                ('father_last_name', models.CharField(blank=True, max_length=50)),
                ('father_first_name', models.CharField(blank=True, max_length=50)),
                ('father_is_baptismal', models.BooleanField(default=False)),
                ('father_baptismal_name', models.CharField(blank=True, max_length=100)),
                ('father_is_renamed', models.BooleanField(default=False)),
                ('father_renamed_name', models.CharField(blank=True, max_length=100)),
                ('father_is_deceased', models.BooleanField(default=False)),
                ('mother_last_name', models.CharField(blank=True, max_length=50)),
                ('mother_first_name', models.CharField(blank=True, max_length=50)),
                ('mother_is_baptismal', models.BooleanField(default=False)),
                ('mother_baptismal_name', models.CharField(blank=True, max_length=100)),
                ('mother_is_renamed', models.BooleanField(default=False)),
                ('mother_renamed_name', models.CharField(blank=True, max_length=100)),
                ('mother_is_deceased', models.BooleanField(default=False)),
                ('free_input', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='app_invitation.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greeting', to='app_invitation.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonecode', models.CharField(blank=True, max_length=20, verbose_name='우편번호')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='지번/도로명 통합 주소')),
                ('e_address', models.CharField(blank=True, max_length=300, verbose_name='영문 지번/도로명 통합 주소')),
                ('address_type', models.CharField(blank=True, max_length=20, verbose_name='주소 타입')),
                ('bcode', models.CharField(blank=True, max_length=20, verbose_name='법정동 코드')),
                ('bname', models.CharField(blank=True, max_length=100, verbose_name='법정동/법정리')),
                ('bname1', models.CharField(blank=True, max_length=100, verbose_name='읍,면동 이름')),
                ('bname2', models.CharField(blank=True, max_length=100, verbose_name='법정동,리 이름')),
                ('e_bname', models.CharField(blank=True, max_length=100, verbose_name='영문 법정동/법정리')),
                ('e_bname1', models.CharField(blank=True, max_length=100, verbose_name='영문 읍,면동 이름')),
                ('e_bname2', models.CharField(blank=True, max_length=100, verbose_name='영문 법정동,리 이름')),
                ('building_code', models.CharField(blank=True, max_length=50, verbose_name='건물 코드')),
                ('building_name', models.CharField(blank=True, max_length=200, verbose_name='건물명')),
                ('sido', models.CharField(blank=True, max_length=50, verbose_name='시도')),
                ('sigungu', models.CharField(blank=True, max_length=50, verbose_name='시군구')),
                ('sigungu_code', models.CharField(blank=True, max_length=20, verbose_name='시군구 코드')),
                ('e_sido', models.CharField(blank=True, max_length=50, verbose_name=' 영문 시도')),
                ('e_sigungu', models.CharField(blank=True, max_length=50, verbose_name='영문 시군구')),
                ('roadname', models.CharField(blank=True, max_length=200, verbose_name='도로명')),
                ('roadname_code', models.CharField(blank=True, max_length=50, verbose_name='도로명 코드')),
                ('roadaddress', models.CharField(blank=True, max_length=300, verbose_name='도로명 주소')),
                ('e_roadaddress', models.CharField(blank=True, max_length=300, verbose_name='영문 도로명 주소')),
                ('jibunadress', models.CharField(blank=True, max_length=300, verbose_name='지번 주소')),
                ('e_jibunadress', models.CharField(blank=True, max_length=300, verbose_name=' 영문 지번 주소')),
                ('detail_address', models.CharField(blank=True, max_length=200, verbose_name='상세 주소')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='app_invitation.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='app_invitation.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['invitation', 'order'], name='app_invitat_invitat_379b21_idx')],
                'constraints': [models.UniqueConstraint(fields=('invitation', 'order'), name='uniq_invitation_order'), models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='ck_gallery_order_non_negative')],
            },
        ),
    ]
