# Generated by Django 5.2.5 on 2025-09-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0004_invitationcalendar_invitationfamily_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationgallery',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='invitationgallery',
            name='uniq_invitation_order',
        ),
        migrations.RemoveConstraint(
            model_name='invitationgallery',
            name='ck_gallery_order_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='invitationgallery',
            name='app_invitat_invitat_379b21_idx',
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='app_invitation',
        ),
        migrations.AlterModelTable(
            name='invitationcalendar',
            table='app_invitationcalendar',
        ),
        migrations.AlterModelTable(
            name='invitationfamily',
            table='app_invitationfamily',
        ),
        migrations.AlterModelTable(
            name='invitationgallery',
            table='app_invitationgallery',
        ),
        migrations.AlterModelTable(
            name='invitationgreeting',
            table='app_invitationgreeting',
        ),
        migrations.AlterModelTable(
            name='invitationmap',
            table='app_invitationmap',
        ),
    ]
