# Generated by Django 5.2.7 on 2025-10-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0005_alter_invitationgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationfamily',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='app_invitation.invitation'),
        ),
    ]
