# Generated by Django 5.2.7 on 2025-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0006_alter_invitationfamily_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationgallery',
            name='image_path',
        ),
        migrations.AddField(
            model_name='invitationgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invitation/gallery/', verbose_name='갤러리 이미지'),
        ),
    ]
