# Generated by Django 5.2.7 on 2025-10-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0007_remove_invitationgallery_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationmap',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='invitationmap',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
