# Generated by Django 5.2.7 on 2025-10-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0008_invitationmap_lat_invitationmap_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmap',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invitationmap',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
