# Generated by Django 5.2.7 on 2025-10-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0009_alter_invitationmap_lat_alter_invitationmap_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='작성자')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호(해시)')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='작성일시')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to='app_invitation.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
