# Generated by Django 5.2.7 on 2025-10-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0010_guestbookentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestbookEntry',
            new_name='Guestbook',
        ),
        migrations.AlterModelOptions(
            name='guestbook',
            options={},
        ),
        migrations.AlterModelTable(
            name='guestbook',
            table='app_guestbook',
        ),
    ]
