# Generated by Django 5.2.7 on 2025-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0011_rename_guestbookentry_guestbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='bride_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_bankname',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='bride_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='휴대폰 번호'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_bankname',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='groom_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='휴대폰 번호'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='father_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='father_bankname',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='휴대폰 번호'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='mother_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='mother_bankname',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='invitationfamily',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_baptismal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='세례명'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_is_baptismal',
            field=models.BooleanField(default=False, verbose_name='세례 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_is_deceased',
            field=models.BooleanField(default=False, verbose_name='고인 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_is_renamed',
            field=models.BooleanField(default=False, verbose_name='개명 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='아버님  성'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='father_renamed_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='개명'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='free_input',
            field=models.CharField(blank=True, max_length=200, verbose_name='자유 입력'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_baptismal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='세례 명'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_is_baptismal',
            field=models.BooleanField(default=False, verbose_name='세례 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_is_deceased',
            field=models.BooleanField(default=False, verbose_name='고인 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_is_renamed',
            field=models.BooleanField(default=False, verbose_name='개명 여부'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='어머님 성'),
        ),
        migrations.AlterField(
            model_name='invitationfamily',
            name='mother_renamed_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='개명'),
        ),
    ]
