# Generated by Django 5.2.7 on 2025-10-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0012_invitation_bride_account_invitation_bride_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_upload_to', verbose_name='갤러리 이미지'),
        ),
    ]
