# Generated by Django 5.2.7 on 2025-10-19 06:49

import app_invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0013_alter_invitationgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.gallery_upload_to, verbose_name='갤러리 이미지'),
        ),
    ]
