# Generated by Django 5.2.7 on 2025-10-19 06:55

import app_invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0014_alter_invitationgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='end_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.invitation_image_upload_to, verbose_name='엔드 이미지'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.invitation_image_upload_to, verbose_name='메인 이미지'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='middle_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.invitation_image_upload_to, verbose_name='중간 이미지'),
        ),
    ]
