# Generated by Django 5.2.7 on 2025-10-19 07:11

import app_invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0015_invitation_end_img_invitation_main_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationgreeting',
            name='greeting_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.greeting_image_upload_to, verbose_name='인사말 이미지'),
        ),
        migrations.AddField(
            model_name='invitationmap',
            name='map_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.map_image_upload_to, verbose_name='인사말 이미지'),
        ),
    ]
