# Generated by Django 5.2.7 on 2025-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0016_invitationgreeting_greeting_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitationname',
            field=models.CharField(default=22, max_length=150, unique=True, verbose_name='초대장 이름'),
            preserve_default=False,
        ),
    ]
