# Generated by Django 5.2.7 on 2025-10-20 07:36

import app_invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0017_invitation_invitationname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'verbose_name': '방명록 - 건드릴 필요 없음', 'verbose_name_plural': '방멱록 - 건드릴 필요 없음'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': '청첩장 기본 정보', 'verbose_name_plural': '청첩장 기본 정보'},
        ),
        migrations.AlterModelOptions(
            name='invitationcalendar',
            options={'verbose_name': '캘린더 - 건드릴 필요 없음', 'verbose_name_plural': '캘린더 - 건드릴 필요 없음'},
        ),
        migrations.AlterModelOptions(
            name='invitationfamily',
            options={'verbose_name': '혼주 정보', 'verbose_name_plural': '혼주 정보'},
        ),
        migrations.AlterModelOptions(
            name='invitationgallery',
            options={'verbose_name': '갤러리 사진 업로드', 'verbose_name_plural': '갤러리 사진 업로드'},
        ),
        migrations.AlterModelOptions(
            name='invitationgreeting',
            options={'verbose_name': '인사말', 'verbose_name_plural': '인사말'},
        ),
        migrations.AlterModelOptions(
            name='invitationmap',
            options={'verbose_name': '위치', 'verbose_name_plural': '위치'},
        ),
        migrations.AlterField(
            model_name='invitationmap',
            name='map_img',
            field=models.ImageField(blank=True, null=True, upload_to=app_invitation.models.map_image_upload_to, verbose_name='약도 이미지'),
        ),
    ]
