# Generated by Django 5.2.7 on 2025-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0018_alter_guestbook_options_alter_invitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='조회수'),
        ),
    ]
