# Generated by Django 5.2.7 on 2025-10-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0019_invitation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
    ]
