# Generated by Django 5.2.7 on 2025-10-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invitation', '0020_alter_invitation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
